name: dart_converter
description: A dart (json) converter
# version: 1.0.0
homepage: https://github.com/TheKingDave/dart_converter

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
